"""
GitHub repository collector.

This collector searches GitHub repositories using planner-generated search
queries and converts the results into Article objects.
"""

from __future__ import annotations

import os
from typing import Any
import requests

from config.settings import(
    GITHUB_API_BASE_URL,
    GITHUB_API_VERSION,
    GITHUB_REPOSITORIES_PER_QUERY,
    REQUEST_TIMEOUT,
    USER_AGENT,
    GITHUB_TRUST_SCORE
)
from agents.collectors.base import BaseCollector
from state.models import (
    Article, 
    SearchQuery,
    Category,
    Source,
    SourceType,
)
from utils.datetime import parse_iso_datetime
from utils.ids import generate_article_id
from utils.logger import get_logger

logger = get_logger(__name__)

class GitHubCollector(BaseCollector):
    """
    Collect AI-related repositories from the GitHub Search API.
    """

    def __init__(self) -> None:
        self._token = os.getenv("GITHUB_API_TOKEN")

        if not self._token:
            raise ValueError(
                "GITHUB_API_TOKEN environment variable is not set. "
                "Please add it to your .env file."
            )

    def _build_headers(self) -> dict[str,str]:
        """
        Build request headers for the GitHub REST API.
        """

        return {
            "Authorization": f"Bearer {self._token}",
            "Accept": f"application/vnd.github+json",
            "User-Agent": USER_AGENT,
            "X-GitHub-Api-Version": GITHUB_API_VERSION,
        }
    
    def _search_repositories(
            self,
            query: SearchQuery,
    ) -> list[dict[str, Any]]:
        """
        Search GitHub repositories for a planner-generated query.

        Args:
            query: Search query generated by the planner.

        Returns:
            A list of raw GitHub repositories JSON objects.

        Raises:
        requests.HTTPError:
            If the request to the GitHub API fails.
        """
        response = requests.get(
            f"{GITHUB_API_BASE_URL}/search/repositories",
            headers=self._build_headers(),
            params={
                "q": query.query,
                "sort": "updated",
                "order": "desc",
                "per_page": GITHUB_REPOSITORIES_PER_QUERY,
            },
            timeout=REQUEST_TIMEOUT,
        )

        response.raise_for_status()
        
        payload = response.json()

        return payload.get("items", [])
    
    def _parse_repository(
            self,
            repository: dict[str, Any],
    ) -> Article:
        """
        Convert GitHub repository into the standard Article model.

        Args:
            repository: Raw GitHub repository JSON.
        
        Returns:
            Parsed Article instance.
        
        """
        repository_url = repository["html_url"]

        source = Source(
            name="GitHub",
            url="https://github.com",
            source_type=SourceType.GITHUB,
            is_official=False,
            trust_score=GITHUB_TRUST_SCORE,
        )

        return Article(
            id = generate_article_id(repository_url),
            title = repository["full_name"],
            url=repository_url,
            source = source,
            published_at=parse_iso_datetime(
                repository["updated_at"]
            ),
            summary = repository.get("description"),
            content=None,
            category=Category.OPEN_SOURCE,
            tags = repository.get("topics", []),
            relevance_score = 0.0,
            trust_score = source.trust_score,
        )


    logger.info("Searching GitHub Repositories.")

    def _duplicate_articles(
            self,
            articles: list[Article],
    ) -> list[Article]:
        """
        Remove duplicate Github repositories.

        Duplicate repositories can appear beacuse multiple search queires may match the same repository.

        Args:
            articles: Parsed GitHub articles.

        Returns:
            List of unique articles.
        """

        unique_articles: dict[str, Article] = {}

        for article in articles:
            unique_articles[article.id] = article

        duplicate_count = len(articles) - len(unique_articles)

        return list(unique_articles.values()), duplicate_count

    def collect(
            self,
            queries: list[SearchQuery],
    ) -> list[Article]:
        """
        Collect GitHub repositories for all planner-generated queries.

        Args:
            queries: Planner-generated GitHub search queries.

        Returns:
            List of parsed Article objects.
        """

        articles: list[Article] = []
        
        for query in queries:

            try:
                repositories = self._search_repositories(query)

                for repository in repositories:
                    articles.append(
                        self._parse_repository(repository)
                    )

            except requests.RequestException as exc:
                logger.exception(
                    "GitHub request failed for query '%s': %s",
                    query.query,
                    exc,
                )

            except (KeyError, ValueError) as exc:
                logger.exception(
                    "Failed to parse GitHub repository for query '%s': %s ",
                    query.query,
                    exc,
                )
        
        unique_articles, duplicate_count = self._duplicate_articles(articles)
        logger.info(
            "Collected %d unique GitHub repositories from %d search queries (%d duplicates removed).",
            len(unique_articles),
            len(queries),
            duplicate_count,
        )
                
        return unique_articles

    


def github_collector_node(state: dict[str, Any]) -> dict[str, Any]:
    """
    LangGraph node for collecting GitHub repositories.
    """

    collector = GitHubCollector()

    articles = collector.collect(
        state["search_queries"]
    )

    return {
        "articles": articles,
    }