from enum import Enum
from pydantic import BaseModel, Field
from datetime import datetime
from datetime import date
from typing import Optional

class SourceType(str, Enum):
    """
    Defines where a news article was collected from.
    """

    OFFICIAL = "official"
    RSS = "rss"
    GITHUB = "github"
    HUGGINGFACE = "huggingface"
    ARXIV = "arxiv"
    WEB_SEARCH = "web_search"


class SourceGroup(str, Enum):
    """
        Editorial grouping of a news source.

        Used by the Selection Agent to maintain
        balanced representation across different
        types of AI news sources.
    """

    OFFICIAL = "official"
    RESEARCH = "research"
    OPEN_SOURCE = "open_source"
    AI_NEWS = "ai_news"
    COMMUNITY = "community"

class Category(str, Enum):
    """
    Defines the category of an AI news article.
    """

    MODEL = "Model"
    AGENT = "Agent"
    RESEARCH = "Research"
    OPEN_SOURCE = "Open Source"
    TOOL = "Tool"
    INFRASTRUCTURE = "Infrastructure"
    COMPANY = "Company"
    OTHER = "Other"

class Source(BaseModel):
    """
    Represents the source from which a news article was collected.
    """

    name: str = Field(
        ...,
        description="Human-readable source name (e.g., OpenAI, Github)"
    )

    url: str = Field(
        ...,
        description="Official URL of the source"
    )

    source_type: SourceType = Field(
        ...,
        description="Type of source"
    )

    group: SourceGroup = Field(
        ...,
        description="Editorial grouping used by the Selection Agent."
    )

    is_official: bool = Field(
        default=False,
        description="Whether this is an official company source"
    )

    trust_score: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Source reliability score between 0 and 1"
    )

class Article(BaseModel):
    """
    Standard news article used throughout the application.
    Every collector must return this model.
    """

    id: str = Field(
        ...,
        description="Unique identifier for the article"
    )

    title: str = Field(
        ...,
        description = "News headline"
    )

    url: str= Field(
        ...,
        description="Original article URL"
    )

    source: Source = Field(
        ...,
        description=" Source information"
    )

    published_at: datetime = Field(
        ...,
        description="Publication date and time"
    )

    summary: Optional[str] = Field(
        default=None,
        description="Generate summary"
    )

    content: Optional[str] = Field(
        default=None,
        description="Full article content"
    ) 

    category: Optional[Category] = Field(
        default=None,
        description="Article category"
    )

    tags: list[str] = Field(
        default_factory=list,
        description="Keywords"
    )

    ranking_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Final ranking score assigned by the Ranking Agent."
    )

    trust_score: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Trust score inherited from source"
    )


class Priority(str, Enum):
    """
    Priority level for search query.
    """

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"

class QueryStatus(str, Enum):
    """
    Current execution status of a search query.
    """

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"

class ExecutionStatus(str, Enum):
    """
    Represents the overall workflow execution status.
    """

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class SearchQuery(BaseModel):
    """
    Represents a search task generated by the planner Agent.
    """

    query: str = Field(
        ...,
        description="Search query generated by the planner."
    )

    target_source: SourceType = Field(
        ...,
        description="Target source where this query should be executed."
    )

    priority: Priority = Field(
        default=Priority.MEDIUM,
        description="Execution priority"
    )

    status: QueryStatus = Field(
        default=QueryStatus.PENDING,
        description="Current execution status."
    )

    created_at: datetime = Field(
        default_factory=datetime.now,
        description="Query creation timestamp."
    )


class Newsletter(BaseModel):
    """
    Represents the final newsletter generated by the Newsletter Agent.
    """

    title: str = Field(
        ...,
        description="Title of the newsletter."
    )

    newsletter_date: date=Field(
        ...,
        description="Newsletter date."
    )

    articles: list[Article] = Field(
        default_factory=list,
        description="List of processed articles."
    )

    html_content: str | None = Field(
        default=None,
        description="Generated HTML newsletter."
    )

    markdown_content: str | None = Field(
        default=None,
        description="Generated Markdown newsletter."
    )

    generated_at: datetime = Field(
        default_factory=datetime.now,
        description="Newsletter generation timestamp."
    )



class ExecutionInfo(BaseModel):
    """
    Represents metadata about one execution of the AI News workflow.
    """

    execution_id: str = Field(
        ...,
        description="Unique execution identifier."
    )

    execution_status: ExecutionStatus = Field(
        default=ExecutionStatus.PENDING,
        description="Current workflow status."
    )

    started_at: datetime = Field(
        default_factory=datetime.now,
        description="Workflow start time."
    )

    completed_at: datetime | None = Field(
        default=None,
        description="Workflow completion time."
    )

    total_articles: int = Field(
        default=0,
        ge=0,
        description="Number of collected articles."
    )

    error_message: str | None = Field(
        default=None,
        description="Failure reason, if any."
    )